export default {
  API_URL: process.env.NEXT_PUBLIC_API_URL || process.env.PLASMO_PUBLIC_API_URL || "",
  PLAYGROUND_API_URL: process.env.NEXT_PUBLIC_PLAYGROUND_API_URL || process.env.PLASMO_PUBLIC_PLAYGROUND_API_URL || "",
  AZURE_OPENAI_ENDPOINT_SE: process.env.NEXT_PUBLIC_AZURE_OPENAI_ENDPOINT_SE || process.env.PLASMO_PUBLIC_AZURE_OPENAI_ENDPOINT_SE || "",
  AZURE_OPENAI_KEY_SE: process.env.NEXT_PUBLIC_AZURE_OPENAI_KEY_SE || process.env.PLASMO_PUBLIC_AZURE_OPENAI_KEY_SE || "",
  ENV: process.env.NEXT_PUBLIC_ENV || process.env.PLASMO_PUBLIC_ENV || "",
  WEBSOCKET_URL: process.env.NEXT_PUBLIC_WEBSOCKET_URL || process.env.PLASMO_PUBLIC_WEBSOCKET_URL || "",
};
